#!/bin/bash
set -e

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

java -jar /opt/resource/github-release-delete-resource.jar out $destination
